Add limburgish locale using an english fallback
CLDR script failed as limburgish doesn't have a localized name it seems,
so we fall back to its English name instead

Without this fix, the generation failed:

```
% script/i18n/generate_languages_translations
Generate 57 translation files in
CLDR database version 44 missing
script/i18n/generate_languages_translations:48:in
'CldrTranslations#language_name': undefined method 'capitalize' for nil
(NoMethodError)

    language_name.capitalize
                 ^^^^^^^^^^^
    from script/i18n/generate_languages_translations:166:in
'GenerateTranslationFiles.yaml_content'
    from script/i18n/generate_languages_translations:158:in 'block in
GenerateTranslationFiles.create_translation_file'
    from script/i18n/generate_languages_translations:156:in
'Pathname#open'
    from script/i18n/generate_languages_translations:156:in
'GenerateTranslationFiles.create_translation_file'
    from script/i18n/generate_languages_translations:150:in 'block in
GenerateTranslationFiles.call'
    from script/i18n/generate_languages_translations:149:in 'Array#each'
    from script/i18n/generate_languages_translations:149:in
'GenerateTranslationFiles.call'
    from script/i18n/generate_languages_translations:184:in '<main>'
```