Fix failing AccountController#register spec
With an OpenProject config containing private plugins this spec will
fail with the following Error:

    ActionView::Template::Error: undefined method `allow_password_changes?' for nil:NilClass
    ./app/models/user.rb:377:in `change_password_allowed?'

This failure was most likely previously obscured because
`render_views` was not enabled.

Signed-off-by: Alex Coles <alex@alexbcoles.com>