Use sprockets backport-compatible sass-rails fork
With 3.2.x sass-rails release, we hit NoMethodErrors with the Living
Style Guide attempting to handle asset helpers:

    undefined method `image_path' for nil:NilClass

This resolves the issue, for now, but moving to Rails 4 is the better
medium-term solution.

See also https://discussion.heroku.com/t/using-the-rails-4-asset-pipeline-in-rails-3-apps-for-faster-deploys/205

Signed-off-by: Alex Coles <alex@alexbcoles.com>