fix anonymize script failing at form configuration groups and attributes
kind for groups and attribute_key for attributes needs to have specific
values so must not be randomized, otherwise constraints fail

INFO:  UPDATE form_configuration_groups SET kind=MD5(kind) WHERE NOT
kind = '';
ERROR:  new row for relation "form_configuration_groups" violates check
constraint "form_configuration_groups_kind"
DETAIL:  Failing row contains (6, 5, 1,
1b1cc7f086b3f074da452bc3129981eb, null, User stories and bugs, 1,
2026-10-08 19:03:49.228553+00, 2026-10-08 19:03:49.228553+00).
CONTEXT:  SQL statement "UPDATE form_configuration_groups SET
kind=MD5(kind) WHERE NOT kind = '';"