Do not use Storages::Storage model in migrations.
It breaks the migration process if we define store_attribute and
try to use model class without store_attribute column in the db.
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x00007f7aa00163b0 @precision=nil, @scale=nil, @limit=nil> (NoMethodError)

        @store_accessor = subtype.accessor
                                 ^^^^^^^^^
/usr/local/bundle/gems/store_attribute-1.1.1/lib/store_attribute/active_record/type/typed_store.rb:33:in `initialize'
/usr/local/bundle/gems/store_attribute-1.1.1/lib/store_attribute/active_record/type/typed_store.rb:25:in `new'
/usr/local/bundle/gems/store_attribute-1.1.1/lib/store_attribute/active_record/type/typed_store.rb:25:in `create_from_type'
/usr/local/bundle/gems/store_attribute-1.1.1/lib/store_attribute/active_record/store.rb:188:in `block in _define_store_attribute'