Fix ArgumentError in QueryRepresenter
quick fixes

```
ArgumentError: Column needs to be set
        from /usr/src/app/lib/api/v3/queries/sort_bys/sort_by_decorator.rb:41:in `initialize'
        from /usr/src/app/lib/api/v3/queries/query_serialization.rb:194:in `new'
        from /usr/src/app/lib/api/v3/queries/query_serialization.rb:194:in `block in map_with_sort_by_as_decorated'
        from /usr/src/app/lib/api/v3/queries/query_serialization.rb:193:in `map'
```