Do not require reform in Gemfile
There appears to be a namespacing conflict with Reform and some
plugin cuke features (manifesting itself in the error below):

    undefined method `new' for Save:Module (NoMethodError)

Signed-off-by: Alex Coles <alex@alexbcoles.com>